import puppeteer from 'puppeteer'
const b = await puppeteer.launch({ headless: 'new', defaultViewport: { width: 1600, height: 900, deviceScaleFactor: 1.5 } })
const pg = await b.newPage()
await pg.goto('http://localhost:5173/#/login', { waitUntil: 'networkidle2' })
await new Promise((r) => setTimeout(r, 1200))
const ins = await pg.$$('input')
await ins[0].type('admin')
await ins[1].type('admin123')
await pg.click('button[type=submit]')
await pg.waitForSelector('.kpi-tile', { timeout: 20000 })
await new Promise((r) => setTimeout(r, 1500))
await pg.click('.profile-chip')
await new Promise((r) => setTimeout(r, 900))
await pg.screenshot({ path: 'screenshots/profile_modal.png' })
await b.close()
console.log('ok')
